#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <QString>
#include <QMap>
#include <QObject>

namespace Constants {

	static const QMap<QString, QString> MAPS = {
	{"guadalcanal", QObject::tr("Guadalcanal")},
	{"wake_island", QObject::tr("Wake Island")},
	{"midway", QObject::tr("Midway")},
	{"malta", QObject::tr("Malta")},
	{"water_midway", QObject::tr("Midway")},
	{"water_coral", QObject::tr("Coral Sea")},
	{"water_guadalcanal", QObject::tr("Guadalcanal")},
	{"honolulu", QObject::tr("Oahu")},
	{"britain", QObject::tr("Britain")},
	{"sicily", QObject::tr("Sicily")},
	{"berlin", QObject::tr("Berlin")},
	{"bulge", QObject::tr("Bulge")},
	{"korsun", QObject::tr("Korsun")},
	{"stalingrad", QObject::tr("Stalingrad")},
	{"stalingrad_w", QObject::tr("Winter Stalingrad")},
	{"krymsk", QObject::tr("Kuban")},
	{"port_moresby", QObject::tr("Port Moresby")},
	{"ruhr", QObject::tr("Ruhr")},
	{"water_east_china_sea", QObject::tr("East China Sea")},
	{"water", QObject::tr("Pacific Ocean")},
	{"peleliu", QObject::tr("Peleliu")},
	{"arcade_africa_canyon", QObject::tr("Canyon, Africa")},
	{"arcade_asia_4roads", QObject::tr("Mountain Ridge, China")},
	{"arcade_phiphi_crater", QObject::tr("African Island, Crater")},
	{"arcade_phiphi_island", QObject::tr("African Island")},
	{"arcade_alps", QObject::tr("Alpine Meadows")},
	{"guam", QObject::tr("Guam")},
	{"saipan", QObject::tr("Saipan")},
	{"iwo_jima", QObject::tr("Iwo Jima")},
	{"philippine_sea", QObject::tr("Philippine Sea")},
	{"korea", QObject::tr("Korea")},
	{"mozdok", QObject::tr("Mozdok")},
	{"mozdok_winter", QObject::tr("Winter Mozdok")},
	{"norway", QObject::tr("Norway")},
	{"khalkhin_gol", QObject::tr("Khalkhin Gol")},
	{"avg_kursk", QObject::tr("Kursk - tank battle")},
	{"kursk", QObject::tr("Kursk")},
	{"air_race_phiphi_islands", QObject::tr("Tropical Island")},
	{"moscow", QObject::tr("Moscow")},
	{"avg_eastern_europe", QObject::tr("Eastern Europe")},
	{"avg_poland", QObject::tr("Poland")},
	{"normandy", QObject::tr("Coast of France")},
	{"arcade_ireland", QObject::tr("Ireland")},
	{"avg_mozdok", QObject::tr("Mozdok - tank battle")},
	{"avg_berlin", QObject::tr("Berlin - tank battle")},
	{"avg_krymsk", QObject::tr("Kuban - tank battle")},
	{"avg_stalingrad_factory", QObject::tr("Stalingrad - tank battle")},
	{"avg_rheinland", QObject::tr("Crossing over the Rhine")},
	{"avg_volokolamsk", QObject::tr("Volokolamsk")},
	{"avg_tunisia_desert", QObject::tr("Tunisia")},
	{"avg_snow_alps", QObject::tr("Frozen Pass")},
	{"avg_africa_desert", QObject::tr("El Alamein")},
	{"air_africa_desert", QObject::tr("El Alamein")},
	{"avg_finland", QObject::tr("Finland")},
	{"avg_iberian_castle", QObject::tr("Iberian Castle")},
	{"avg_normandy", QObject::tr("Normandy")},
	{"avg_hurtgen", QObject::tr("Hurtgen Forest")},
	{"avg_korea_lake", QObject::tr("The 38th parallel")},
	{"avg_karelia_forest_a", QObject::tr("Karelia")},
	{"avg_karpaty_passage", QObject::tr("Carpathians")},
	{"avg_abandoned_factory", QObject::tr("Abandoned Factory")},
	{"arcade_africa_seashore", QObject::tr("Deserted Coast")},
	{"dover_strait", QObject::tr("Dover Strait")},
	{"arcade_rice_terraces", QObject::tr("Rice Terraces")},
	{"arcade_canyon_snow", QObject::tr("Iron Range")},
	{"arcade_norway_fjords", QObject::tr("Fjords")},
	{"arcade_norway_green", QObject::tr("Green Ridge")},
	{"arcade_norway_plain", QObject::tr("Foothills")},
	{"arcade_phiphi_crater_rocks", QObject::tr("Pacific Hidden Base")},
	{"arcade_snow_rocks", QObject::tr("Top of the World")},
	{"arcade_zhang_park", QObject::tr("Grave Robbers' Cliffs")},
	{"avg_european_fortress", QObject::tr("White Rock Fortress")},
	{"avg_guadalcanal", QObject::tr("Guadalcanal - tank battle")},
	{"avg_ireland", QObject::tr("Ash River")},
	{"avg_port_novorossiysk", QObject::tr("Novorossiysk")},
	{"avg_training_ground", QObject::tr("Shooting Range")},
	{"caribbean_islands", QObject::tr("Caribbean Islands")},
	{"hangar_airfield_2014", QObject::tr("Military Airfield")},
	{"hangar_military_base", QObject::tr("Military Base")},
	{"hangar_military_base_ny", QObject::tr("Military Base 2017")},
	{"spain", QObject::tr("Spain")},
	{"zhengzhou", QObject::tr("Zhengzhou")},
	{"avg_ardennes", QObject::tr("Bulge - tank battle")},
	{"avg_fulda", QObject::tr("Fulda Gap")},
	{"avg_japan", QObject::tr("Imperial Gardens")},
	{"avg_sector_montmedy", QObject::tr("Maginot Line")},
	{"avg_sector_montmedy_snow", QObject::tr("Maginot Line")},
	{"avg_lazzaro_italy", QObject::tr("Italy")},
	{"avg_american_valley", QObject::tr("American Desert")},
	{"avg_alaska_town", QObject::tr("Alaska Town")},
	{"air_vietnam", QObject::tr("Vietnam")},
	{"avg_vietnam_hills", QObject::tr("Vietnam Hills")},
	{"avg_egypt_sinai", QObject::tr("Sinai")},
	{"avg_syria", QObject::tr("Middle East")},
	{"air_ladoga", QObject::tr("Ladoga")},
	{"air_afghan", QObject::tr("Afghanistan")},
	{"avn_fiji", QObject::tr("Fiji")},
	{"avn_alps_fjord", QObject::tr("Green Mountains Gulf")},
	{"arcade_mediterranean", QObject::tr("Greece")},
	{"avn_volcanic_island", QObject::tr("Volcanic Island")},
	{"avg_container_port", QObject::tr("Cargo Port")},
	{"avn_peleliu", QObject::tr("Palau Islands")},
	{"avn_japan", QObject::tr("Japanese Port")},
	{"avn_south_africa", QObject::tr("South Africa")},
	{"avn_new_zeland_cape", QObject::tr("New Zealand Cape")},
	{"avn_finland_islands", QObject::tr("South Kvarken")},
	{"avg_sweden", QObject::tr("Sweden")},
	{"air_denmark", QObject::tr("Denmark")},
	{"air_smolensk", QObject::tr("Smolensk")},
	{"hurtgen", QObject::tr("Hürtgen")},
	{"sector_montmedy", QObject::tr("Maginot Line")},
	{"tunisia", QObject::tr("Tunisia")},
	{"arcade_tabletop_mountain", QObject::tr("Guiana Highlands")},
	{"avg_lazzaro_italy_new_city", QObject::tr("Campania")},
	{"avn_aleutian_islands", QObject::tr("Aleutian Islands")},
	{"avg_kursk_villages", QObject::tr("Fire Arc")},
	{"air_skyscraper_city", QObject::tr("City")},
	{"avg_nuclear_incident", QObject::tr("Ground Zero")},
	{"avg_soviet_suburban", QObject::tr("Seversk-13")},
	{ "avg_soviet_suburban_snow", QObject::tr("Seversk-13") },
	{"avg_western_europe", QObject::tr("Spaceport")},
	{"arcade_floating_islands", QObject::tr("Floating Islands")},
	{"avn_sunken_city", QObject::tr("Drowned City")},
	{"avg_red_desert", QObject::tr("Red Desert")},
	{"avg_breslau", QObject::tr("Breslau")},
	{"firing_range", QObject::tr("Proving Ground")},
	{"avn_northwestern_islands", QObject::tr("Vyborg Bay")},
	{"air_equatorial_island", QObject::tr("Bourbon Island")},
	{"avg_aral_sea", QObject::tr("Aral Sea")},
	{"air_israel", QObject::tr("Golan Heights")},
	{"avg_israel", QObject::tr("Sun City")},
	{"avg_abandoned_town", QObject::tr("Abandoned Town")},
	{"avg_greece", QObject::tr("Attica")},
	{"air_south_eastern_city", QObject::tr("Southeastern City")},
	{"avg_northern_india", QObject::tr("Pradesh")},
	{"avn_san_francisco", QObject::tr("Golden Bay")},
	{"air_grand_canyon", QObject::tr("Rocky Canyon")},
	{"avg_arctic", QObject::tr("Arctic")},
	{"avg_northern_valley", QObject::tr("Golden Quarry")},
	{"air_pyrenees", QObject::tr("Mountain Valleys")},
	{"avn_franz_josef_land", QObject::tr("Franz Josef Land")},
	{"avg_soviet_range", QObject::tr("Test Site-2271")},
	{"air_southeastern_cliffs", QObject::tr("Rocky Pillars")},
	{"avg_vlaanderen", QObject::tr("Flanders")},
	{"air_kamchatka", QObject::tr("Volcano Valley")},
	{"avg_netherlands", QObject::tr("North Holland")},
	{"avn_norway_islands", QObject::tr("Norway Islands")},
	{"avg_forgotten_land", QObject::tr("Forgotten Lands")},
	{"air_mysterious_valley", QObject::tr("Mysterious Valley")},
	{"avn_bering_sea", QObject::tr("Bering Sea")}
	};

	enum class Difficulty {
		ARCADE = 0,
		REALISTIC = 5,
		SIMULATOR = 10
	};
}


#endif // CONSTANTS_H